<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.XUnit" Version="3.0.19"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZCore\ZCore.csproj"/>
    <ProjectReference Include="..\ZSerilog\ZSerilog.csproj"/>
  </ItemGroup>

</Project>
