<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>IZ.Client</AssemblyName>
    <RootNamespace>IZ.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZCore\ZCore.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StrawberryShake.Transport.Http" Version="15.1.11" />
  </ItemGroup>

</Project>
