<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>IZ.Client</AssemblyName>
    <RootNamespace>IZ.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZCore\ZCore.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GoogleAnalyticsTracker.Simple" Version="7.0.1"/>
    <PackageReference Include="Semver" Version="3.0.0"/>
    <PackageReference Include="StrawberryShake.Transport.Http" Version="15.1.10" />
  </ItemGroup>

</Project>
