<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>IZ.Schema</RootNamespace>
    <AssemblyName>IZ.Schema</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="15.1.3" />
    <PackageReference Include="HotChocolate.Types.Scalars" Version="15.1.3" />
    <PackageReference Include="HotChocolate.Types.Scalars.Upload" Version="15.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZCore\ZCore.csproj" />
  </ItemGroup>
</Project>
