<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>IZ.Data</AssemblyName>
    <RootNamespace>IZ.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.10" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);NETSDK1188</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZCore\ZCore.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Seed\"/>
  </ItemGroup>

</Project>
